#!/usr/bin/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="spamassassin"
check_container_initialized

### File Permissions Check
mkdir -p /var/lib/spamassassin
mkdir -p /var/log/spamassassin
mkdir -p /var/run/spamassassin
chown -R spamassassin:spamassassin /var/lib/spamassassin /var/run/spamassassin /var/log/spamassassin

### Assets Setup
if [ ! -f /etc/mail/spamassassin/local.cf ] ; then
	print_notice "Copying Default Configuration"
	cp -R /assets/mail /etc/
	#chown -R spamassassin:spamassassin /etc/mail
fi

### Update Spamassassin Ruleset
if [ ! -f /var/lib/spamassassin/.initialized ] ; then		
	print_notice "Updating Rulesets"
	s6-envuidgid spamassassin sa-update
    touch /var/lib/spamassassin/.initialized
fi

### Set Debug Mode
if var_true $DEBUG_MODE ; then
	DEBUG_ARG="--debug" 
fi
	
liftoff

print_info "Starting spamassassin"
exec spamd --username spamassassin --nouser-config --syslog=/var/log/spamassassin/spamd.log -pidfile /var/run/spamassassin/spamd.pid --helper-home-dir /var/lib/spamassassin --ip-address 0.0.0.0:737 --allowed-ips 0.0.0.0/0 $DEBUG_ARG
