#!/usr/bin/with-contenv bash

source /assets/functions/*
PROCESS_NAME="spamassassin"

### File Permissions Check
mkdir -p /var/lib/spamassassin
mkdir -p /var/log/spamassassin
mkdir -p /var/run/spamassassin
chown -R spamassassin:spamassassin /var/lib/spamassassin /var/run/spamassassin /var/log/spamassassin

### Assets Setup
if [ ! -f /etc/mail/spamassassin/local.cf ] ; then
	echo '** [spamasassin] Copying Default Configuration'
	cp -R /assets/mail /etc/
	#chown -R spamassassin:spamassassin /etc/mail
fi

### Update Spamassassin Ruleset
if [ ! -f /var/lib/spamassassin/.initialized ] ; then		
	echo '** [spamasassin] Updating Rulesets'
	s6-envuidgid spamassassin sa-update
    touch /var/lib/spamassassin/.initialized
fi

### Set Debug Mode
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
	DEBUG_ARG="--debug" 
fi
	
liftoff

print_info "Starting spamassassin"
exec spamd --username spamassassin --nouser-config --syslog=/var/log/spamassassin/spamd.log -pidfile /var/run/spamassassin/spamd.pid --helper-home-dir /var/lib/spamassassin --ip-address 0.0.0.0:737 --allowed-ips 0.0.0.0/0 $DEBUG_ARG
