#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service both single
PROCESS_NAME="spamassassin"

check_container_initialized
check_service_initialized init

parse_arguments
liftoff

print_start "Starting spamassassin"
exec spamd \
			--username spamassassin \
            --group spamassassin \
			--allowed-ips 0.0.0.0/0 \
			--siteconfigpath ${CONFIG_PATH} \
			--helper-home-dir ${DATA_PATH} \
			--ip-address 0.0.0.0:${LISTEN_PORT} \
			--max-children=${CHILD_MAX} \
			--max-conn-per-child=${CHILD_MAX_CONNECTIONS} \
			--max-spare=${CHILD_MAX_SPARE} \
			--min-children=${CHILD_MIN} \
			--min-spare=${CHILD_MIN_SPARE} \
			--pidfile ${PID_PATH}${PID_FILE} \
			--syslog=${LOG_PATH}${LOG_FILE} \
			--timeout-child=${TIMEOUT_CHILD} \
			--timeout-tcp=${TIMEOUT_TCP} \
			--nouser-config $debug_arg $learning_arg $round_robin_arg
